### ISSUE TITLE
T5EncoderModel error

### ISSUE THREAD

**Issue by vtan05** [Dai-Wenxun/MotionLCM#1]
Hi, I tried testing your code but I'm getting an error on the T5 Encoder. I tried re-downloading the T5 encoder but it still did not work.   
![image](https://github.com/Dai-Wenxun/MotionLCM/assets/42295449/7d59ffec-f47b-43f3-92d6-fed5ab0ce489)

**Comment by Dai-Wenxun** [comment]
Have the pre-trained weights for T5 been correctly downloaded to the ``${MotionLCM}/deps/`` directory?


![image](https://github.com/Dai-Wenxun/MotionLCM/assets/58767402/82e94f0f-2b76-4c44-aa10-004a3796b26e)

**Comment by vtan05** [comment]
Yes, I just followed the instructions from the README. But I still got the same error. 
![image](https://github.com/Dai-Wenxun/MotionLCM/assets/42295449/6910d61a-3efe-4183-a19f-524a93c7fd2e)

**Comment by vtan05** [comment]
Ah! I already solved it. I reinstalled git lfs and downloaded the t5 transformer again from huggingface. It is now working. Thank you for your prompt reponse!

**Comment by 2019211753** [comment]
I also encountered this error and solved it by installing git lfs.

**Comment by he-nantian** [comment]
I wonder the criteria for selecting from T5 & CLIP models, do you have any insights for it?
