### ISSUE TITLE
Why is MotionLCM's  Traj.err and Loc.err lower than OmniControl?

### ISSUE THREAD

**Issue by 2019211753** [Dai-Wenxun/MotionLCM#10]
OmniControl utilizes two modules to control the trajectory, whereas MotionLCM relies solely on the ControlNet. Additionally, there are other differences: for instance, MotionLCM trains ControlNet after pretraining LCM, while OmniControl trains ControlNet and Diffusion together. Moreover, MotionLCM incorporates a controlling loss, which OmniControl does not use. However, I am still puzzled as to why MotionLCM exhibits lower Traj.err and Loc.err compared to OmniControl. Could you please help me understand this? Thank you in advance for your assistance!

**Comment by Dai-Wenxun** [comment]
OmniControl is the primary baseline for our comparisons. To ensure a fair comparison (i.e., only introducing control signals through ControlNet), we remove [OmniControl's guided diffusion](https://github.com/neu-vi/OmniControl/blob/main/diffusion/gaussian_diffusion.py#L450). Under this setting, our `Traj.err` and `Loc.err` indeed outperform OmniControl.

We found that OmniControl's control capabilities primarily come from guided diffusion, but this guiding process is extremely time-consuming. Therefore, we are also exploring how to introduce such guidance to MotionLCM (possibly in the latent space?) to enhance its control performance. We welcome any discussions on this topic. Thank you!

![image](https://github.com/Dai-Wenxun/MotionLCM/assets/58767402/a44665ef-12e3-4e8b-b498-8765c4789a34)

**Comment by 2019211753** [comment]
@Dai-Wenxun Thanks for your reply. It solves my question. I did see this table, but I just didn't understand the meaning of OmniControl without the "*". I also believe that heuristic classifier guidance is a technology worth exploring.
