### ISSUE TITLE
About pretrained MLD

### ISSUE THREAD

**Issue by DunyangNi** [Dai-Wenxun/MotionLCM#11]
Is it possible to train MotionLCM on a checkpoint pretrained with the original MLD repo?
If not, what are the configurations you use to pretrain the MLD?

**Comment by Dai-Wenxun** [comment]
If I remember correctly, we train MLD on the original MLD repo and then directly load the pre-trained checkpoint to train MotionLCM. But there are some useless attributes in the pre-trained checkpoint as shown below. You only need to remain the ``'state_dict'``.

![image](https://github.com/Dai-Wenxun/MotionLCM/assets/58767402/d1fc1bc1-b861-4b2e-89cd-46a15145e28b)

The LAST step is to delete one useless parameter saved in 'denoiser', `'denoiser.mem_pos.pe'`. This param is not been used in denoiser but the author left it carelessly.

Finally, save the cleaned checkpoint which is a `dict` with ONE key `state_dict`. 

If you encounter any issues in this process, feel free to inform me. hahaha

**Comment by Dai-Wenxun** [comment]
Feel free to open  this issue
