### ISSUE TITLE
 python -m train_motionlcm --cfg configs/motionlcm_t2m.yaml报错（motionlcm_t2m.yaml未修改）

### ISSUE THREAD

**Issue by fengshan0713** [Dai-Wenxun/MotionLCM#12]
Traceback (most recent call last):
  File "/home/aligames/miniconda3/envs/motionlcm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aligames/miniconda3/envs/motionlcm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/workspace/yfs/t2m/MotionLCM/train_motionlcm.py", line 440, in <module>
    main()
  File "/mnt/workspace/yfs/t2m/MotionLCM/train_motionlcm.py", line 262, in main
    max_rp1, min_fid = validation()
  File "/home/aligames/miniconda3/envs/motionlcm/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/yfs/t2m/MotionLCM/train_motionlcm.py", line 250, in validation
    metrics = base_model.allsplit_epoch_end()
  File "/mnt/workspace/yfs/t2m/MotionLCM/mld/models/modeltype/base.py", line 39, in allsplit_epoch_end
    metrics_dict = getattr(self, metric).compute()
  File "/home/aligames/miniconda3/envs/motionlcm/lib/python3.10/site-packages/torchmetrics/metric.py", line 616, in wrapped_func
    value = _squeeze_if_scalar(compute(*args, **kwargs))
  File "/mnt/workspace/yfs/t2m/MotionLCM/mld/models/metrics/tm2t.py", line 85, in compute
    assert count_seq > self.R_size
AssertionError
Steps:   0%|                                                                              | 0/96000 [00:03<?, ?it/s]

**Comment by Dai-Wenxun** [comment]
From the error message:
```
assert count_seq > self.R_size
```
it seems the `count_seq` is 0, this is because there is no data for validation.

Could you please show me your `datasets/` ? If you have prepared the dataset, this folder should look like this:

![image](https://github.com/user-attachments/assets/3a803b8f-34ed-41b9-bfca-2f77dbbb650a)

If you don't prepare this, please follow this to finish it. 

![image](https://github.com/user-attachments/assets/ad25ca10-0915-4b5c-9853-b0f3f09d0f6d)

**Comment by fengshan0713** [comment]
I have tried debugging and found that：count_seq,self.R_size ：5，32
<img width="825" alt="729FDFE6-6612-4D8C-8AC0-66B21C1EC268" src="https://github.com/user-attachments/assets/58fe6456-52e3-49ed-934e-e06e8a6729f3">
and i have prepared the dataset：
<img width="378" alt="9B75DB36-EC5B-43FF-8C91-4C7D858E2972" src="https://github.com/user-attachments/assets/190c6e82-23b9-4d95-82c2-c2ed7f14f9d2">
but I have used this method:

![20240723095816](https://github.com/user-attachments/assets/d18b19e4-0f2e-4f26-a1a9-10fe284a79af)

I'll try your method to prepare the data again

**Comment by fengshan0713** [comment]
And can't I train the model from 0? I found that the training model must use pretrain_madel: 'experiences_t2m/mld_humanml/mld_humanml. ckpt', can it only be fine-tune？

**Comment by Dai-Wenxun** [comment]
> And can't I train the model from 0? I found that the training model must use pretrain_madel: 'experiences_t2m/mld_humanml/mld_humanml. ckpt', can it only be fine-tune？

MotionLCM is a distillation model, so it must be distilled from a pre-trained model.

**Comment by Dai-Wenxun** [comment]
there are 20000+ examples in:

![image](https://github.com/user-attachments/assets/10ddac15-4242-41b4-bbc6-09591dd2e356)

Maybe you don't fully prepare the data???

**Comment by fengshan0713** [comment]
> there are 20000+ examples in:
> 
> ![image](https://private-user-images.githubusercontent.com/58767402/351181830-10ddac15-4242-41b4-bbc6-09591dd2e356.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTk3NDEsIm5iZiI6MTcyMTcxOTQ0MSwicGF0aCI6Ii81ODc2NzQwMi8zNTExODE4MzAtMTBkZGFjMTUtNDI0Mi00MWI0LWJiYzYtMDk1OTFkZDJlMzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA3MjQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTc4ZWRjMDVjNTdmMGY1YWNiZGRiYjU0ZWY4ZmFkZmE5OTY5NjljMmM1YWJmZGVlNTlkNDNkNTAzNTZmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AurkPmFRvF5xG3jApObTVusuRPrie2vfXrAmNxFN_w0)
> 
> Maybe you don't fully prepare the data???

![image](https://github.com/user-attachments/assets/51aeafd5-400a-4078-b5cf-f806e73df49f)
I should have fully prepare the data

**Comment by Dai-Wenxun** [comment]
wtf, the training starts with a validation using the data included in the `test.txt`. Does the test.txt is abnormal?

![image](https://github.com/user-attachments/assets/32e782ca-18e8-42ad-95d1-cab38488f604)

**Comment by fengshan0713** [comment]
thinks！test.txt is abnormal！just 5 lines.!!!!
