### ISSUE TITLE
name 'datasets' is not defined. Did you mean: 'dataset'?

### ISSUE THREAD

**Issue by Axian12138** [Dai-Wenxun/MotionLCM#15]
hi, thanks for your great work!
but in demo.py line 109, maybe it should be `test_dataloader = dataset.test_dataloader()` 
name 'datasets' is not defined. Did you mean: 'dataset'?

**Comment by Dai-Wenxun** [comment]
Yes! Thank you for reporting this issue. Could you please pull a request to fix it? Thank you!
