### ISSUE TITLE
No permission to access the link in https://github.com/Dai-Wenxun/MotionLCM/issues/6

### ISSUE THREAD

**Issue by zymcloud** [Dai-Wenxun/MotionLCM#17]
When I was processing the dataset, I found that I did not have permission to access the Google Drive link https://github.com/Dai-Wenxun/MotionLCM/issues/6, I would like to ask what went wrong. Thank you very much.
![Uploading 捕获.PNG…]()

**Comment by Dai-Wenxun** [comment]
Yeah. Now we have to process the dataset according to the official repo. (sad)

**Comment by zymcloud** [comment]
Thank you for your reply.
