### ISSUE TITLE
V1 and V2 Difference

### ISSUE THREAD

**Issue by andypinxinliu** [Dai-Wenxun/MotionLCM#21]
I see there is huge difference in performance, may i know how and why MLD++ and MotionLCMv2 will have very significant improvement?

**Comment by Dai-Wenxun** [comment]
we ll released a blog to explain for the community in the next few days

**Comment by Dai-Wenxun** [comment]
Blog link: https://huggingface.co/blog/wxDai/motionlcm-v2
