### ISSUE TITLE
HumanML3D Preparation Guide (Unofficial)

### ISSUE THREAD

**Issue by Zeyi-Lin** [Dai-Wenxun/MotionLCM#6]
🎉I have successfully run through the training process of MotionLCM, this is a great job!

For preparing the HumanML3D dataset, two steps need to be done:

1. Download all files from the [Google Drive](https://drive.google.com/drive/folders/1e437ofkMW_C6KnP2ef7JY_UuX7XN9_zZ) to the `datasets/humanml3d` directory, which include `train.txt`, `val.txt`, `test.txt`, `train_val.txt`, `all.txt`, `Std.npy`, `Mean.npy` and `new_joint_vecs.rar`. Unrar the `new_joins_vecs.rar`.

2.  `texts.zip`: Download it from [here](https://github.com/EricGuo5513/HumanML3D/tree/main/HumanML3D) and unzip it in the  `datasets/humanml3d` directory.

**Comment by LinghaoChan** [comment]
Thanks for the suggestion. The guidances have been updated in the readme.

**Comment by robbinhan** [comment]
> 🎉I have successfully run through the training process of MotionLCM, this is a great job!
> 
> In preparing the training dataset, two steps need to be taken:
> 
> 1. Download all files from this [Google Drive](https://drive.google.com/drive/folders/1e437ofkMW_C6KnP2ef7JY_UuX7XN9_zZ) to the `datasets/humanml3d` directory.
> 2. Unrar the three compressed files `new_joins.rar`, `new_joins_vecs.rar`, and `texts.rar`, and the final directory structure should be as shown in the README.

I did not find the texts.rar file.

**Comment by Zeyi-Lin** [comment]
> > 🎉I have successfully run through the training process of MotionLCM, this is a great job!
> > In preparing the training dataset, two steps need to be taken:
> > 
> > 1. Download all files from this [Google Drive](https://drive.google.com/drive/folders/1e437ofkMW_C6KnP2ef7JY_UuX7XN9_zZ) to the `datasets/humanml3d` directory.
> > 2. Unrar the three compressed files `new_joins.rar`, `new_joins_vecs.rar`, and `texts.rar`, and the final directory structure should be as shown in the README.
> 
> I did not find the texts.rar file.

` texts.zip ` download at https://github.com/EricGuo5513/HumanML3D/tree/main/HumanML3D

**Comment by robbinhan** [comment]
@Zeyi-Lin Thank you very much

**Comment by Zeyi-Lin** [comment]
> @Zeyi-Lin Thank you very much

I’m happy to help. Good luck.

**Comment by zymcloud** [comment]
I am sorry, I  meet the problem that I don't have permission to access this link Google Drive.

**Comment by dipakn** [comment]
Hey, can you reopen the Google file?, because i cannot download the file,
